spring:
  application:
    name: social-network-app

  datasource:
    username: root
    password: Manh2004
    url: jdbc:mysql://localhost:3306/social-network

  liquibase:
    change-log: classpath:/db/changelog/appchange-log.xml
    liquibase-schema: social-network

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 10

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenmanhlc10@gmail.com
    password: aaof rvju disf hati
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



jwt:
  secret: IHog2o7M6EPmoJ4Y4WBiLbvbCJ+AnYe3C1VmUQdW4gg=

frontend:
  url: http://127.0.0.1:5500

cloudinary:
  api_key: 829565713471837
  api_secret: oHpiWWc8qqRFZUkj-kBtXhsVcJ8
  cloud_name: djuq2enmy

azure:
  api_key: 9AmCriorbFDfgJSUEN4foN8uTELaxggb9KSafvABdGfRCbXu40ZqJQQJ99CBACqBBLyXJ3w3AAAHACOGoBIS
  endpoint: https://be-app-content-safety.cognitiveservices.azure.com